version: '3.8'
name: taskmaster
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=taskmaster
    ports:
      - "5432:5432"
